# 使用するプロキシの設定名
use_proxy = "example"

# PuTTY などでプロキシの設定をせずに繋ぐための設定
# 41000番ポートへの接続をappの22番ポートにしたい場合は "41000->app:22"
reverse = [
  "41000->app:22",
  "41001->images:22",
]

# 接続先になる既存のプロキシの設定例

[proxies.example]
host = "127.0.0.1"
http_port = 1080
socks_port = 1081
username = "your-user-name"
password = "hack-me"
